name: "Is my code great?"
description: "Executes the is-my-code-great CLI tool to validate code quality."
author: "AlienEngineer"
inputs:
  verbose:
    description: "Enable verbose output"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: "execute script"
      shell: bash
      run: |
        VERBOSE_FLAG=""
        if [[ "${{ inputs.verbose }}" == "true" ]]; then
          VERBOSE_FLAG="-v"
        fi

        ${{ github.action_path }}/bin/is-my-code-great $VERBOSE_FLAG > results.txt
        echo "VALIDATION_OUTPUT<<EOF" >> $GITHUB_ENV
        cat results.txt >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: "Comment PR with results"
      uses: actions/github-script@v7
      if: ${{ github.event_name == 'pull_request' }}
      with:
        script: |
          const results = process.env.VALIDATION_OUTPUT || 'No results found.';
          const commentBody = `### Is My Code Great Results:\n\n\`\`\`\n${results}\n\`\`\``;


          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          const existingComment = comments.find(c => c.body.includes('Is My Code Great Results:'));

          if (existingComment) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
            });
          }

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: commentBody
          });

    - name: "Add results to summary"
      shell: bash
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo "### Is My Code Great Results:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "${VALIDATION_OUTPUT:-No results found.}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
